name: arm7_tdmi
description: >
  An emulator for the ARM7-TDMI processor.
version: 0.0.1
authors:
  - Matan Lurey <matan@lurey.org>
homepage: https://github.com/matanlurey/gba.dart

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  quiver:

dev_dependencies:
  test:
